version: "3.9"

services:
  php84:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - 8401:80 # PHP 8.4 → 8400
      - 5173:5173 #node
    volumes:
      - ./src/portfolio:/var/www/html
    environment:
      - APP_ENV=local
      - TZ=Asia/Tokyo
    extra_hosts:
      - "host.docker.internal:host-gateway"
